import type { UserDTO } from "@/types/user-management";

export const mockUsers: UserDTO[] = [
  {
    id: "user_001",
    account: "admin",
    name: "超级管理员",
    role: "SUPER_ADMIN",
    status: "ACTIVE",
    organizationId: "seed_default_group",
    organization: { id: "seed_default_group", name: "AI Newline 集团" },
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "user_002",
    account: "sh_manager",
    name: "张伟",
    role: "BRANCH_MANAGER",
    status: "ACTIVE",
    organizationId: "org_branch_001",
    organization: { id: "org_branch_001", name: "上海分公司" },
    createdAt: "2026-01-12T08:00:00.000Z",
  },
  {
    id: "user_003",
    account: "sh_emp_01",
    name: "李明",
    role: "EMPLOYEE",
    status: "ACTIVE",
    organizationId: "org_branch_001",
    organization: { id: "org_branch_001", name: "上海分公司" },
    createdAt: "2026-01-15T08:00:00.000Z",
  },
  {
    id: "user_004",
    account: "sh_emp_02",
    name: "王芳",
    role: "EMPLOYEE",
    status: "DISABLED",
    organizationId: "org_branch_001",
    organization: { id: "org_branch_001", name: "上海分公司" },
    createdAt: "2026-01-20T08:00:00.000Z",
  },
  {
    id: "user_005",
    account: "bj_manager",
    name: "刘洋",
    role: "BRANCH_MANAGER",
    status: "ACTIVE",
    organizationId: "org_branch_002",
    organization: { id: "org_branch_002", name: "北京分公司" },
    createdAt: "2026-01-16T08:00:00.000Z",
  },
  {
    id: "user_006",
    account: "bj_emp_01",
    name: "陈静",
    role: "EMPLOYEE",
    status: "ACTIVE",
    organizationId: "org_branch_002",
    organization: { id: "org_branch_002", name: "北京分公司" },
    createdAt: "2026-02-01T08:00:00.000Z",
  },
  {
    id: "user_007",
    account: "bj_emp_02",
    name: "赵磊",
    role: "EMPLOYEE",
    status: "ACTIVE",
    organizationId: "org_branch_002",
    organization: { id: "org_branch_002", name: "北京分公司" },
    createdAt: "2026-02-10T08:00:00.000Z",
  },
  {
    id: "user_008",
    account: "gz_manager",
    name: "孙晓",
    role: "BRANCH_MANAGER",
    status: "DISABLED",
    organizationId: "org_branch_003",
    organization: { id: "org_branch_003", name: "广州分公司" },
    createdAt: "2026-02-05T08:00:00.000Z",
  },
  {
    id: "user_009",
    account: "sz_emp_01",
    name: "周杰",
    role: "EMPLOYEE",
    status: "ACTIVE",
    organizationId: "org_branch_004",
    organization: { id: "org_branch_004", name: "深圳分公司" },
    createdAt: "2026-02-22T08:00:00.000Z",
  },
  {
    id: "user_010",
    account: "sh_emp_03",
    name: "吴敏",
    role: "EMPLOYEE",
    status: "ACTIVE",
    organizationId: "org_branch_001",
    organization: { id: "org_branch_001", name: "上海分公司" },
    createdAt: "2026-03-01T08:00:00.000Z",
  },
];
